notify {
    'Hello Mercedes':
    # $facts[os]:
}
notify { $::osfamily: }
# notify { $::architecture: }
# notify { $::augeasversion: }
# notify { $::blockdevice_sda_model: }
# notify { $::blockdevice_sda_size: }
# notify { $::blockdevice_sda_vendor: }
# notify { $::blockdevice_sdb_model: }
# notify { $::blockdevice_sdb_size: }
# notify { $::blockdevice_sdb_vendor: }
# notify { $::blockdevice_sr0_model: }
# notify { $::blockdevice_sr0_size: }
# notify { $::blockdevice_sr0_vendor: }
# notify { $::blockdevices: }
# notify { $::dhcp_servers: }
# notify { $::domain: }
# notify { $::facterversion: }
# notify { $::filesystems: }
# notify { $::fqdn: }
# notify { $::gid: }
# notify { $::hostname: }
# notify { $::id: }
# notify { $::interfaces: }
# notify { $::ipaddress: }
# notify { $::ipaddress_lo: }
# notify { $::ipaddress_wlan0: }
# notify { $::is_virtual: }
# notify { $::kernel: }
# notify { $::kernelmajversion: }
# notify { $::kernelrelease: }
# notify { $::kernelversion: }
# notify { $::lsbdistcodename: }
# notify { $::lsbdistdescription: }
# notify { $::lsbdistid: }
# notify { $::lsbdistrelease: }
# notify { $::lsbmajdistrelease: }
# notify { $::lsbminordistrelease: }
# notify { $::lsbrelease: }
# notify { $::macaddress: }
# notify { $::macaddress_eth0: }
# notify { $::macaddress_wlan0: }
# notify { $::memoryfree: }
# notify { $::memoryfree_mb: }
# notify { $::memorysize: }
# notify { $::memorysize_mb: }
# notify { $::mtu_eth0: }
# notify { $::mtu_lo: }
# notify { $::mtu_wlan0: }
# notify { $::netmask: }
# notify { $::netmask_lo: }
# notify { $::netmask_wlan0: }
# notify { $::network_lo: }
# notify { $::network_wlan0: }
# notify { $::operatingsystem: }
# notify { $::operatingsystemmajrelease: }
# notify { $::operatingsystemrelease: }
# notify { $::os: }
# notify { $::osfamily: }
# notify { $::partitions: }
# notify { $::path: }
# notify { $::physicalprocessorcount: }
# notify { $::processor0: }
# notify { $::processor1: }
# notify { $::processor2: }
# notify { $::processor3: }
# notify { $::processor4: }
# notify { $::processor5: }
# notify { $::processor6: }
# notify { $::processor7: }
# notify { $::processorcount: }
# notify { $::processors: }
# notify { $::ps: }
# notify { $::puppetversion: }
# notify { $::rubyplatform: }
# notify { $::rubysitedir: }
# notify { $::rubyversion: }
# notify { $::selinux: }
# notify { $::swapfree: }
# notify { $::swapfree_mb: }
# notify { $::swapsize: }
# notify { $::swapsize_mb: }
# notify { $::system_uptime: }
notify { $facts[timezone]: }
# notify { $::uniqueid: }
# notify { $::uptime: }
# notify { $::uptime_days: }
# notify { $::uptime_hours: }
# notify { $::uptime_seconds: }
# notify { $::virtual: }
